import type { VehicleBrand } from "./vehicle-catalog.js";

/**
 * Referentiel des marques et modeles vendus en France et en Europe (retour, 2026-09-10) :
 * generations recentes, utilitaires, electriques, voitures sans permis. Noms tels que les
 * constructeurs les ecrivent (accents compris). Une marque absente reste acceptee, mise en forme
 * proprement par le referentiel. Les finitions restent en texte libre (champ « version »).
 */
export const VEHICLE_BRANDS: readonly VehicleBrand[] = [
  { name: "Abarth", models: ["500", "500e", "595", "600e", "695"] },
  { name: "Aiways", models: ["U5", "U6"] },
  { name: "Aixam", models: ["City", "Coupé", "Crossline", "Crossover", "Minauto", "e-City"] },
  { name: "Alfa Romeo", models: ["4C", "Giulia", "Giulietta", "Junior", "Stelvio", "Tonale"] },
  { name: "Alpina", models: ["B3", "B4", "B5", "B8", "XB7"] },
  { name: "Alpine", models: ["A110", "A290", "A390"] },
  {
    name: "Aston Martin",
    models: ["DB11", "DB12", "DBS", "DBX", "Valhalla", "Vantage"],
  },
  {
    name: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A6 e-tron",
      "A7",
      "A8",
      "e-tron GT",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q6 e-tron",
      "Q7",
      "Q8",
      "Q8 e-tron",
      "R8",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "RS Q3",
      "RS Q8",
      "S3",
      "S4",
      "S5",
      "SQ5",
      "TT",
    ],
  },
  {
    name: "Bentley",
    models: ["Bentayga", "Continental GT", "Continental GTC", "Flying Spur"],
  },
  {
    name: "BMW",
    models: [
      "Série 1",
      "Série 2",
      "Série 2 Active Tourer",
      "Série 2 Gran Coupé",
      "Série 3",
      "Série 4",
      "Série 5",
      "Série 7",
      "Série 8",
      "i4",
      "i5",
      "i7",
      "iX",
      "iX1",
      "iX2",
      "iX3",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
      "X1",
      "X2",
      "X3",
      "X3 M",
      "X4",
      "X5",
      "X5 M",
      "X6",
      "X7",
      "XM",
      "Z4",
    ],
  },
  {
    name: "BYD",
    models: [
      "Atto 2",
      "Atto 3",
      "Dolphin",
      "Dolphin Surf",
      "Han",
      "Seal",
      "Seal U",
      "Sealion 7",
      "Tang",
    ],
  },
  { name: "Cadillac", models: ["Escalade", "Lyriq"] },
  { name: "Caterham", models: ["Seven"] },
  { name: "Chevrolet", models: ["Camaro", "Corvette"] },
  {
    name: "Citroën",
    models: [
      "Ami",
      "Berlingo",
      "C1",
      "C3",
      "C3 Aircross",
      "C4",
      "C4 X",
      "C5 Aircross",
      "C5 X",
      "ë-C3",
      "ë-C4",
      "Jumper",
      "Jumpy",
      "SpaceTourer",
    ],
  },
  {
    name: "Cupra",
    models: ["Ateca", "Born", "Formentor", "Leon", "Raval", "Tavascan", "Terramar"],
  },
  {
    name: "Dacia",
    models: ["Bigster", "Duster", "Jogger", "Logan", "Sandero", "Sandero Stepway", "Spring"],
  },
  { name: "Dodge", models: ["Challenger", "Charger", "Durango"] },
  { name: "DS", models: ["DS 3", "DS 4", "DS 7", "DS 9", "N°8"] },
  {
    name: "Ferrari",
    models: [
      "12Cilindri",
      "296 GTB",
      "296 GTS",
      "812 GTS",
      "812 Superfast",
      "F8 Spider",
      "F8 Tributo",
      "Portofino M",
      "Purosangue",
      "Roma",
      "Roma Spider",
      "SF90 Spider",
      "SF90 Stradale",
    ],
  },
  {
    name: "Fiat",
    models: [
      "500",
      "500e",
      "500X",
      "600",
      "Doblò",
      "Ducato",
      "Grande Panda",
      "Panda",
      "Scudo",
      "Talento",
      "Tipo",
    ],
  },
  { name: "Fisker", models: ["Ocean"] },
  {
    name: "Ford",
    models: [
      "Capri",
      "Explorer",
      "Fiesta",
      "Focus",
      "Kuga",
      "Mustang",
      "Mustang Mach-E",
      "Puma",
      "Ranger",
      "Tourneo Connect",
      "Tourneo Courier",
      "Tourneo Custom",
      "Transit",
      "Transit Connect",
      "Transit Courier",
      "Transit Custom",
    ],
  },
  { name: "Genesis", models: ["G70", "G80", "GV60", "GV70", "GV80"] },
  { name: "Honda", models: ["Civic", "CR-V", "e:Ny1", "Honda e", "HR-V", "Jazz", "ZR-V"] },
  {
    name: "Hyundai",
    models: [
      "Bayon",
      "i10",
      "i20",
      "i30",
      "Inster",
      "Ioniq 5",
      "Ioniq 6",
      "Ioniq 9",
      "Kona",
      "Santa Fe",
      "Staria",
      "Tucson",
    ],
  },
  { name: "Ineos", models: ["Grenadier"] },
  { name: "Isuzu", models: ["D-Max"] },
  { name: "Iveco", models: ["Daily"] },
  { name: "Jaguar", models: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF"] },
  {
    name: "Jeep",
    models: ["Avenger", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  },
  { name: "KGM", models: ["Korando", "Musso", "Rexton", "Tivoli", "Torres"] },
  {
    name: "Kia",
    models: [
      "Ceed",
      "EV3",
      "EV6",
      "EV9",
      "Niro",
      "Picanto",
      "ProCeed",
      "Rio",
      "Sorento",
      "Soul",
      "Sportage",
      "Stonic",
      "XCeed",
    ],
  },
  { name: "Lamborghini", models: ["Huracán", "Revuelto", "Temerario", "Urus"] },
  { name: "Lancia", models: ["Ypsilon"] },
  {
    name: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  { name: "Leapmotor", models: ["B10", "C10", "T03"] },
  { name: "Lexus", models: ["ES", "LBX", "LC", "LM", "NX", "RX", "RZ", "UX"] },
  { name: "Ligier", models: ["JS50", "JS60", "Myli"] },
  { name: "Lotus", models: ["Eletre", "Emeya", "Emira", "Evora"] },
  { name: "Lucid", models: ["Air", "Gravity"] },
  { name: "Lynk & Co", models: ["01", "02"] },
  { name: "MAN", models: ["TGE"] },
  {
    name: "Maserati",
    models: ["Ghibli", "GranCabrio", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  },
  { name: "Maxus", models: ["eDeliver 3", "eDeliver 7", "eDeliver 9", "Mifa 9", "T90"] },
  {
    name: "Mazda",
    models: ["CX-30", "CX-5", "CX-60", "CX-80", "Mazda2", "Mazda3", "MX-30", "MX-5"],
  },
  { name: "McLaren", models: ["720S", "750S", "Artura", "GT", "GTS"] },
  {
    name: "Mercedes-AMG",
    models: [
      "A 35",
      "A 45 S",
      "C 43",
      "C 63 S E Performance",
      "CLA 45 S",
      "E 53",
      "G 63",
      "GLE 53",
      "GLE 63 S",
      "GT",
      "GT 63",
      "SL 63",
    ],
  },
  {
    name: "Mercedes-Benz",
    models: [
      "AMG GT",
      "Citan",
      "CLA",
      "CLE",
      "Classe A",
      "Classe B",
      "Classe C",
      "Classe E",
      "Classe G",
      "Classe S",
      "Classe V",
      "EQA",
      "EQB",
      "EQE",
      "EQE SUV",
      "EQS",
      "EQS SUV",
      "EQV",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "SL",
      "Sprinter",
      "Vito",
    ],
  },
  { name: "MG", models: ["Cyberster", "EHS", "HS", "MG3", "MG4", "MG5", "S5", "ZS"] },
  { name: "Microcar", models: ["Dué", "M.Go"] },
  {
    name: "Mini",
    models: ["Aceman", "Cabrio", "Clubman", "Cooper 3 portes", "Cooper 5 portes", "Countryman"],
  },
  { name: "Mitsubishi", models: ["ASX", "Colt", "Eclipse Cross", "Outlander", "Space Star"] },
  { name: "Morgan", models: ["Plus Four", "Plus Six", "Super 3"] },
  {
    name: "Nissan",
    models: [
      "Ariya",
      "Interstar",
      "Juke",
      "Leaf",
      "Micra",
      "Primastar",
      "Qashqai",
      "Townstar",
      "X-Trail",
    ],
  },
  { name: "Omoda", models: ["5", "9"] },
  {
    name: "Opel",
    models: [
      "Astra",
      "Combo",
      "Corsa",
      "Crossland",
      "Frontera",
      "Grandland",
      "Mokka",
      "Movano",
      "Vivaro",
      "Zafira",
    ],
  },
  {
    name: "Peugeot",
    models: [
      "108",
      "208",
      "2008",
      "308",
      "3008",
      "408",
      "5008",
      "508",
      "Boxer",
      "e-208",
      "e-2008",
      "e-308",
      "e-3008",
      "Expert",
      "Partner",
      "Rifter",
      "Traveller",
    ],
  },
  { name: "Polestar", models: ["2", "3", "4"] },
  {
    name: "Porsche",
    models: ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  },
  {
    name: "Renault",
    models: [
      "Arkana",
      "Austral",
      "Captur",
      "Clio",
      "Espace",
      "Kadjar",
      "Kangoo",
      "Koleos",
      "Master",
      "Mégane",
      "Mégane E-Tech",
      "Rafale",
      "Renault 4 E-Tech",
      "Renault 5 E-Tech",
      "Scénic E-Tech",
      "Symbioz",
      "Talisman",
      "Trafic",
      "Twingo",
      "Zoe",
    ],
  },
  { name: "Rolls-Royce", models: ["Cullinan", "Dawn", "Ghost", "Phantom", "Spectre", "Wraith"] },
  { name: "Seat", models: ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco"] },
  {
    name: "Škoda",
    models: ["Elroq", "Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Scala", "Superb"],
  },
  { name: "Smart", models: ["#1", "#3", "#5", "forfour", "fortwo"] },
  { name: "Subaru", models: ["Crosstrek", "Forester", "Impreza", "Outback", "Solterra"] },
  { name: "Suzuki", models: ["Across", "Ignis", "Jimny", "S-Cross", "Swace", "Swift", "Vitara"] },
  { name: "Tesla", models: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"] },
  {
    name: "Toyota",
    models: [
      "Aygo X",
      "bZ4X",
      "C-HR",
      "Camry",
      "Corolla",
      "Corolla Cross",
      "GR86",
      "GR Yaris",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "Mirai",
      "Prius",
      "Proace",
      "Proace City",
      "Proace Verso",
      "RAV4",
      "Supra",
      "Yaris",
      "Yaris Cross",
    ],
  },
  {
    name: "Volkswagen",
    models: [
      "Amarok",
      "Arteon",
      "Caddy",
      "California",
      "Crafter",
      "Golf",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID.7",
      "ID. Buzz",
      "Multivan",
      "Passat",
      "Polo",
      "T-Cross",
      "T-Roc",
      "Taigo",
      "Tayron",
      "Tiguan",
      "Touareg",
      "Touran",
      "Transporter",
      "up!",
    ],
  },
  {
    name: "Volvo",
    models: ["EC40", "EX30", "EX40", "EX90", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
  },
  { name: "Xpeng", models: ["G6", "G9", "P7"] },
  { name: "Zeekr", models: ["001", "7X", "X"] },
];
